### PR TITLE
Version bump 1.0.1

### PR DESCRIPTION
**Pull request by isaachall**
* Includes the fix for Ruby 2.2.0

### CODE REVIEW

**Comment by drewish** [comment]
+1

**Comment by sanemat** [comment]
@isaachall @drewish would you release v1.0.1 to rubygems.org? I want to use v1.0.1!
https://rubygems.org/gems/druuid

**Comment by drewish** [comment]
@sanemat yeah sorry, we're reaching out to the previous dev who'd created the gem to get added to it.

**Comment by drewish** [comment]
@sanemat it's published. thanks for your patience.

**Comment by sanemat** [comment]
@drewish thanks! :heart_eyes:

**Pull request merged**
